### ISSUE TITLE
From Mbed OS to FreeRTOS

### ISSUE THREAD

**Issue by git-cerbero** [janjongboom/b-l475e-iot01a-audio-mbed#1]
Hi everyone
I need your help on a university project.
I own a stm-32l475 board, and for the project I'm developing I'm using FreeRTOS. Specifically, I am trying to use the board microphone (MP34DT01) to create a voice-to-text translator.
I managed to find this project, but I understand very little about mbed os and I can't adapt it to FreeRTOS.
Could anyone help me?
I thank you very much
Good evening

**Comment by janjongboom** [comment]
Hi @cerbero-dj, I can't give you any feedback for a FreeRTOS port, but https://github.com/janjongboom/b-l475e-iot01a-audio-mbed/blob/master/MP34DT01/stm32l475e_iot01_irq_handler.c is the only file that is specific to Mbed, but it uses a normal CMSIS function to register the interrupt so it should work on FreeRTOS too. The rest of the driver is not Mbed specific (all the code in https://github.com/janjongboom/b-l475e-iot01a-audio-mbed/tree/master/MP34DT01).
