### ISSUE TITLE
Using this Library with HAL

### ISSUE THREAD

**Issue by SevHub** [janjongboom/b-l475e-iot01a-audio-mbed#2]
Hello, 
can someone please help me getting this library to run without mbed? ST does not care about its customers and therefore does not provide usable examples for this board, especially none for the microphones. 

I used the only available example they provide (BSP Sensor example) and added this library. 
It compiles which was already surprising for me. However, the line ```int32_t ret = BSP_AUDIO_IN_Init(AUDIO_INSTANCE, &MicParams);``` in the main.c returns -9. 
Debugging a bit deeper, the last line that belongs to this library comes from the file stm32l474e_iot01_clock_conf.c and returns HAL_ERROR: ```status = HAL_RCCEx_PeriphCLKConfig(&RCC_ExCLKInitStruct);```

I guess there is something not set up correctly, which is normally a preset by mbed-os, and unfortunately not explicitly set by this lib. Unfortuately there are literary thousands of possible settings that mbed-os sets and I am just a beginner and understand pretty much nothing.

Has someone used this lib withous mbed already? Is there any working example for the microphones without mbed?

**Comment by janjongboom** [comment]
Hi @SevHub, so I pulled this library out of the https://www.st.com/content/st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm32-embedded-software/stm32-ode-function-pack-sw/fp-ai-sensing1.html - I'm not sure why it's not more present on the board page on the ST site, but I think that's a good starting point.
